export const GET_ALL_CONTACTNUMBER_REQUEST = 'GET_ALL_CONTACTNUMBER_REQUEST';
export const GET_ALL_CONTACTNUMBER_SUCCESS = 'GET_ALL_CONTACTNUMBER_SUCCESS';
export const GET_ALL_CONTACTNUMBER_FAIL = 'GET_ALL_CONTACTNUMBER_FAIL';
export const GET_ALL_CONTACTNUMBER_RESET = 'GET_ALL_CONTACTNUMBER_RESET';

export const GET_SINGLE_CONTACTNUMBER_REQUEST = 'GET_SINGLE_CONTACTNUMBER_REQUEST';
export const GET_SINGLE_CONTACTNUMBER_SUCCESS = 'GET_SINGLE_CONTACTNUMBER_SUCCESS';
export const GET_SINGLE_CONTACTNUMBER_FAIL = 'GET_SINGLE_CONTACTNUMBER_FAIL';
export const GET_SINGLE_CONTACTNUMBER_RESET = 'GET_SINGLE_CONTACTNUMBER_RESET';

export const UPDATE_SINGLE_CONTACTNUMBER_REQUEST = "UPDATE_SINGLE_CONTACTNUMBER_REQUEST";
export const UPDATE_SINGLE_CONTACTNUMBER_SUCCESS = "UPDATE_SINGLE_CONTACTNUMBER_SUCCESS";
export const UPDATE_SINGLE_CONTACTNUMBER_FAIL = "UPDATE_SINGLE_CONTACTNUMBER_FAIL";
export const UPDATE_SINGLE_CONTACTNUMBER_RESET = "UPDATE_SINGLE_CONTACTNUMBER_RESET";