export const GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_REQUEST =
  "GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_REQUEST";
export const GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_SUCCESS =
  "GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_SUCCESS";
export const GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_FAIL =
  "GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_FAIL";
export const GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_RESET =
  "GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_RESET";

export const GET_ALL_OTHER_OPTIONS_FOR_SELECT_REQUEST =
  "GET_ALL_OTHER_OPTIONS_FOR_SELECT_REQUEST";
export const GET_ALL_OTHER_OPTIONS_FOR_SELECT_SUCCESS =
  "GET_ALL_OTHER_OPTIONS_FOR_SELECT_SUCCESS";
export const GET_ALL_OTHER_OPTIONS_FOR_SELECT_FAIL =
  "GET_ALL_OTHER_OPTIONS_FOR_SELECT_FAIL";
export const GET_ALL_OTHER_OPTIONS_FOR_SELECT_RESET =
  "GET_ALL_OTHER_OPTIONS_FOR_SELECT_RESET";

// not needed in teacher dashboard
export const GET_SUBJECT_OPTIONS_FOR_SELECT_REQUEST =
  "GET_SUBJECT_OPTIONS_FOR_SELECT_REQUEST";
export const GET_SUBJECT_OPTIONS_FOR_SELECT_SUCCESS =
  "GET_SUBJECT_OPTIONS_FOR_SELECT_SUCCESS";
export const GET_SUBJECT_OPTIONS_FOR_SELECT_FAIL =
  "GET_SUBJECT_OPTIONS_FOR_SELECT_FAIL";
export const GET_SUBJECT_OPTIONS_FOR_SELECT_RESET =
  "GET_SUBJECT_OPTIONS_FOR_SELECT_RESET";
//not needed in teacher dashboard

export const GET_ENGLISH_DATE_REQUEST = "GET_ENGLISH_DATE_REQUEST";
export const GET_ENGLISH_DATE_SUCCESS = "GET_ENGLISH_DATE_SUCCESS";
export const GET_ENGLISH_DATE_FAIL = "GET_ENGLISH_DATE_FAIL";
export const GET_ENGLISH_DATE_RESET = "GET_ENGLISH_DATE_RESET";

export const GET_LIST_STUDENT_PRESENT_REQUEST =
  "GET_LIST_STUDENT_PRESENT_REQUEST";
export const GET_LIST_STUDENT_PRESENT_SUCCESS =
  "GET_LIST_STUDENT_PRESENT_SUCCESS";
export const GET_LIST_STUDENT_PRESENT_FAIL = "GET_LIST_STUDENT_PRESENT_FAIL";
export const GET_LIST_STUDENT_PRESENT_RESET = "GET_LIST_STUDENT_PRESENT_RESET";

export const GET_LIST_FOR_UPDATE_STUDENT_PRESENT_REQUEST =
  "GET_LIST_FOR_UPDATE_STUDENT_PRESENT_REQUEST";
export const GET_LIST_FOR_UPDATE_STUDENT_PRESENT_SUCCESS =
  "GET_LIST_FOR_UPDATE_STUDENT_PRESENT_SUCCESS";
export const GET_LIST_FOR_UPDATE_STUDENT_PRESENT_FAIL =
  "GET_LIST_FOR_UPDATE_STUDENT_PRESENT_FAIL";
export const GET_LIST_FOR_UPDATE_STUDENT_PRESENT_RESET =
  "GET_LIST_FOR_UPDATE_STUDENT_PRESENT_RESET";

export const GET_LIST_FOR_PRESENT_STUDENT_REQUEST =
  "GET_LIST_FOR_PRESENT_STUDENT_REQUEST";
export const GET_LIST_FOR_PRESENT_STUDENT_SUCCESS =
  "GET_LIST_FOR_PRESENT_STUDENT_SUCCESS";
export const GET_LIST_FOR_PRESENT_STUDENT_FAIL =
  "GET_LIST_FOR_PRESENT_STUDENT_FAIL";
export const GET_LIST_FOR_PRESENT_STUDENT_RESET =
  "GET_LIST_FOR_PRESENT_STUDENT_RESET";

export const POST_LIST_STUDENT_PRESENT_REQUEST =
  "POST_LIST_STUDENT_PRESENT_REQUEST";
export const POST_LIST_STUDENT_PRESENT_SUCCESS =
  "POST_LIST_STUDENT_PRESENT_SUCCESS";
export const POST_LIST_STUDENT_PRESENT_FAIL = "POST_LIST_STUDENT_PRESENT_FAIL";
export const POST_LIST_STUDENT_PRESENT_RESET =
  "POST_LIST_STUDENT_PRESENT_RESET";
