export const GET_ALL_RESOURCES_INITIAL_DATA_REQUEST =
  "GET_ALL_RESOURCES_INITIAL_DATA_REQUEST";
export const GET_ALL_RESOURCES_INITIAL_DATA_SUCCESS =
  "GET_ALL_RESOURCES_INITIAL_DATA_SUCCESS";
export const GET_ALL_RESOURCES_INITIAL_DATA_FAIL =
  "GET_ALL_RESOURCES_INITIAL_DATA_FAIL";
export const GET_ALL_RESOURCES_INITIAL_DATA_RESET =
  "GET_ALL_RESOURCES_INITIAL_DATA_RESET";

export const GET_ALL_INITIAL_DATA_FROM_SUBJECT_REQUEST =
  "GET_ALL_INITIAL_DATA_FROM_SUBJECT_REQUEST";
export const GET_ALL_INITIAL_DATA_FROM_SUBJECT_SUCCESS =
  "GET_ALL_INITIAL_DATA_FROM_SUBJECT_SUCCESS";
export const GET_ALL_INITIAL_DATA_FROM_SUBJECT_FAIL =
  "GET_ALL_INITIAL_DATA_FROM_SUBJECT_FAIL";
export const GET_ALL_INITIAL_DATA_FROM_SUBJECT_RESET =
  "GET_ALL_INITIAL_DATA_FROM_SUBJECT_RESET";

export const GET_ALL_OTHER_OPTIONS_FOR_RESOURCES_SELECT_REQUEST =
  "GET_ALL_OTHER_OPTIONS_FOR_RESOURCES_SELECT_REQUEST";
export const GET_ALL_OTHER_OPTIONS_FOR_RESOURCES_SELECT_SUCCESS =
  "GET_ALL_OTHER_OPTIONS_FOR_RESOURCES_SELECT_SUCCESS";
export const GET_ALL_OTHER_OPTIONS_FOR_RESOURCES_SELECT_FAIL =
  "GET_ALL_OTHER_OPTIONS_FOR_RESOURCES_SELECT_FAIL";
export const GET_ALL_OTHER_OPTIONS_FOR_RESOURCES_SELECT_RESET =
  "GET_ALL_OTHER_OPTIONS_FOR_RESOURCES_SELECT_RESET";

export const GET_ALL_RESOURCES_LIST_REQUEST = "GET_ALL_RESOURCES_LIST_REQUEST";
export const GET_ALL_RESOURCES_LIST_SUCCESS = "GET_ALL_RESOURCES_LIST_SUCCESS";
export const GET_ALL_RESOURCES_LIST_FAIL = "GET_ALL_RESOURCES_LIST_FAIL";
export const GET_ALL_RESOURCES_LIST_RESET = "GET_ALL_RESOURCES_LIST_RESET";

export const GET_CREATE_RESOURCES_REQUEST = "GET_CREATE_RESOURCES_REQUEST";
export const GET_CREATE_RESOURCES_SUCCESS = "GET_CREATE_RESOURCES_SUCCESS";
export const GET_CREATE_RESOURCES_FAIL = "GET_CREATE_RESOURCES_FAIL";
export const GET_CREATE_RESOURCES_RESET = "GET_CREATE_RESOURCES_RESET";

export const POST_RESOURCES_REQUEST = "POST_RESOURCES_REQUEST";
export const POST_RESOURCES_SUCCESS = "POST_RESOURCES_SUCCESS";
export const POST_RESOURCES_FAIL = "POST_RESOURCES_FAIL";
export const POST_RESOURCES_RESET = "POST_RESOURCES_RESET";

export const DOWNLOAD_RESOURCES_REQUEST = "DOWNLOAD_RESOURCES_REQUEST";
export const DOWNLOAD_RESOURCES_SUCCESS = "DOWNLOAD_RESOURCES_SUCCESS";
export const DOWNLOAD_RESOURCES_FAIL = "DOWNLOAD_RESOURCES_FAIL";
export const DOWNLOAD_RESOURCES_RESET = "DOWNLOAD_RESOURCES_RESET";

