export const GET_ALL_OLD_QUESTIONS_TEACHER_REQUEST =
  "GET_ALL_OLD_QUESTIONS_TEACHER_REQUEST";
export const GET_ALL_OLD_QUESTIONS_TEACHER_SUCCESS =
  "GET_ALL_OLD_QUESTIONS_TEACHER_SUCCESS";
export const GET_ALL_OLD_QUESTIONS_TEACHER_FAIL =
  "GET_ALL_OLD_QUESTIONS_TEACHER_FAIL";
export const GET_ALL_OLD_QUESTIONS_TEACHER_RESET =
  "GET_ALL_OLD_QUESTIONS_TEACHER_RESET";

  export const GET_SUBJECT_OF_OLD_QUESTIONS_REQUEST =
  "GET_SUBJECT_OF_OLD_QUESTIONS_REQUEST";
export const GET_SUBJECT_OF_OLD_QUESTIONS_SUCCESS =
  "GET_SUBJECT_OF_OLD_QUESTIONS_SUCCESS";
export const GET_SUBJECT_OF_OLD_QUESTIONS_FAIL =
  "GET_SUBJECT_OF_OLD_QUESTIONS_FAIL";
export const GET_SUBJECT_OF_OLD_QUESTIONS_RESET =
  "GET_SUBJECT_OF_OLD_QUESTIONS_RESET";
  
  export const GET_LIST_OLD_QUESTIONS_TEACHER_REQUEST =
  "GET_LIST_OLD_QUESTIONS_TEACHER_REQUEST";
export const GET_LIST_OLD_QUESTIONS_TEACHER_SUCCESS =
  "GET_LIST_OLD_QUESTIONS_TEACHER_SUCCESS";
export const GET_LIST_OLD_QUESTIONS_TEACHER_FAIL =
  "GET_LIST_OLD_QUESTIONS_TEACHER_FAIL";
export const GET_LIST_OLD_QUESTIONS_TEACHER_RESET =
  "GET_LIST_OLD_QUESTIONS_TEACHER_RESET";

  export const DOWNLOAD_OLD_QUESTIONS_REQUEST = "DOWNLOAD_OLD_QUESTIONS_REQUEST";
  export const DOWNLOAD_OLD_QUESTIONS_SUCCESS = "DOWNLOAD_OLD_QUESTIONS_SUCCESS";
  export const DOWNLOAD_OLD_QUESTIONS_FAIL = "DOWNLOAD_OLD_QUESTIONS_FAIL";
  export const DOWNLOAD_OLD_QUESTIONS_RESET = "DOWNLOAD_OLD_QUESTIONS_RESET";
