export const GET_ALL_SYLLABUS_REQUEST = "GET_ALL_SYLLABUS_REQUEST";
export const GET_ALL_SYLLABUS_SUCCESS = "GET_ALL_SYLLABUS_SUCCESS";
export const GET_ALL_SYLLABUS_FAIL = "GET_ALL_SYLLABUS_FAIL";
export const GET_ALL_SYLLABUS_RESET = "GET_ALL_SYLLABUS_RESET";

export const GET_LIST_SYLLABUS_REQUEST = "GET_LIST_SYLLABUS_REQUEST";
export const GET_LIST_SYLLABUS_SUCCESS = "GET_LIST_SYLLABUS_SUCCESS";
export const GET_LIST_SYLLABUS_FAIL = "GET_LIST_SYLLABUS_FAIL";
export const GET_LIST_SYLLABUS_RESET = "GET_LIST_SYLLABUS_RESET";