export const GET_ALL_ACADEMIC_GRADING_REQUEST =
  "GET_ALL_ACADEMIC_GRADING_REQUEST";
export const GET_ALL_ACADEMIC_GRADING_SUCCESS =
  "GET_ALL_ACADEMID_GRADING_SUCCESS";
export const GET_ALL_ACADEMIC_GRADING_FAIL = "GET_ALL_ACADEMIC_GRADING_FAIL";
export const GET_ALL_ACADEMIC_GRADING_RESET = "GET_ALL_ACADEMIC_GRADING_RESET";

export const GET_SINGLE_ACADEMIC_GRADING_REQUEST =
  "GET_SINGLE_ACADEMIC_GRADING_REQUEST";
export const GET_SINGLE_ACADEMIC_GRADING_SUCCESS =
  "GET_SINGLE_ACADEMIC_GRADING_SUCCESS";
export const GET_SINGLE_ACADEMIC_GRADING_FAIL =
  "GET_SINGLE_ACADEMIC_GRADING_FAIL";
export const GET_SINGLE_ACADEMIC_GRADING_RESET =
  "GET_SINGLE_ACADEMIC_GRADING_RESET";

export const CREATE_ACADEMIC_GRADING_REQUEST =
  "CREATE_ACADEMIC_GRADING_REQUEST";
export const CREATE_ACADEMIC_GRADING_SUCCESS =
  "CREATE_ACADEMIC_GRADING_SUCCESS";
export const CREATE_ACADEMIC_GRADING_FAIL = "CREATE_ACADEMIC_GRADING_FAIL";
export const CREATE_ACADEMIC_GRADING_RESET = "CREATE_ACADEMIC_GRADING_RESET";

export const GET_SINGLE_ACADEMIC_GRADING_EDIT_REQUEST =
  "GET_SINGLE_ACADEMIC_GRADING_EDIT_REQUEST";
export const GET_SINGLE_ACADEMIC_GRADING_EDIT_SUCCESS =
  "GET_SINGLE_ACADEMIC_GRADING_EDIT_SUCCESS";
export const GET_SINGLE_ACADEMIC_GRADING_EDIT_FAIL =
  "GET_SINGLE_ACADEMIC_GRADING_EDIT_FAIL";
export const GET_SINGLE_ACADEMIC_GRADING_EDIT_RESET =
  "GET_SINGLE_ACADEMIC_GRADING_EDIT_RESET";

export const UPDATE_SINGLE_ACADEMIC_GRADING_REQUEST =
  "UPDATE_SINGLE_ACADEMIC_GRADING_REQUEST";
export const UPDATE_SINGLE_ACADEMIC_GRADING_SUCCESS =
  "UPDATE_SINGLE_ACADEMIC_GRADING_SUCCESS";
export const UPDATE_SINGLE_ACADEMIC_GRADING_FAIL =
  "UPDATE_SINGLE_ACADEMIC_GRADING_FAIL";
export const UPDATE_SINGLE_ACADEMIC_GADING_RESET =
  "UPDATE_SINGLE_ACADEMIC_GADING_RESET";
