export const GET_ALL_UPLOADPHOTO_REQUEST = "GET_ALL_UPLOADPHOTO_REQUEST";
export const GET_ALL_UPLOADPHOTO_SUCCESS = "GET_ALL_UPLOADPHOTO_SUCCESS";
export const GET_ALL_UPLOADPHOTO_FAIL = "GET_ALL_UPLOADPHOTO_FAIL";
export const GET_ALL_UPLOADPHOTO_RESET = "GET_ALL_UPLOADPHOTO_RESET";

export const UPLOADPHOTO_REQUEST = "UPLOADPHOTO_REQUEST";
export const UPLOADPHOTO_SUCCESS = "UPLOADPHOTO_SUCCESS";
export const UPLOADPHOTO_FAIL = "UPLOADPHOTO_FAIL";
export const UPLOADPHOTO_RESET = "UPLOADPHOTO_RESET";
