export const GET_ALL_EDUCATION_REQUEST = 'GET_ALL_EDUCATION_REQUEST';
export const GET_ALL_EDUCATION_SUCCESS = 'GET_ALL_EDUCATION_SUCCESS';
export const GET_ALL_EDUCATION_FAIL = 'GET_ALL_EDUCATION_FAIL';
export const GET_ALL_EDUCATION_RESET = 'GET_ALL_EDUCATION_RESET';

// export const GET_SINGLE_EDUCATION_REQUEST = 'GET_SINGLE_EDUCATION_REQUEST';
// export const GET_SINGLE_EDUCATION_SUCCESS = 'GET_SINGLE_EDUCATION_SUCCESS';
// export const GET_SINGLE_EDUCATION_FAIL = 'GET_SINGLE_EDUCATION_FAIL';
// export const GET_SINGLE_EDUCATION_RESET = 'GET_SINGLE_EDUCATION_RESET';

export const CREATE_SINGLE_EDUCATION_REQUEST = "CREATE_SINGLE_EDUCATION_REQUEST";
export const CREATE_SINGLE_EDUCATION_SUCCESS = "CREATE_SINGLE_EDUCATION_SUCCESS";
export const CREATE_SINGLE_EDUCATION_FAIL = "CREATE_SINGLE_EDUCATION_FAIL";
export const CREATE_SINGLE_EDUCATION_RESET = "CREATE_SINGLE_EDUCATION_RESET";

export const GET_ALL_EDUCATION_CREATE_REQUEST = 'GET_ALL_EDUCATION_CREATE_REQUEST';
export const GET_ALL_EDUCATION_CREATE_SUCCESS = 'GET_ALL_EDUCATION_CREATE_SUCCESS';
export const GET_ALL_EDUCATION_CREATE_FAIL = 'GET_ALL_EDUCATION_CREATE_FAIL';
export const GET_ALL_EDUCATION_CREATE_RESET = 'GET_ALL_EDUCATION_CREATE_RESET';

export const EDUCATION_CREATE_REQUEST = 'EDUCATION_CREATE_REQUEST';
export const EDUCATION_CREATE_SUCCESS = 'EDUCATION_CREATE_SUCCESS';
export const EDUCATION_CREATE_FAIL = 'EDUCATION_CREATE_FAIL';
export const EDUCATION_CREATE_RESET = 'EDUCATION_CREATE_RESET';