export const GET_ALL_CONTACTADDRESS_REQUEST = 'GET_ALL_CONTACTADDRESS_REQUEST';
export const GET_ALL_CONTACTADDRESS_SUCCESS = 'GET_ALL_CONTACTADDRESS_SUCCESS';
export const GET_ALL_CONTACTADDRESS_FAIL = 'GET_ALL_CONTACTADDRESS_FAIL';
export const GET_ALL_CONTACTADDRESS_RESET = 'GET_ALL_CONTACTADDRESS_RESET';

export const GET_SINGLE_CONTACTADDRESS_REQUEST = 'GET_SINGLE_CONTACTADDRESS_REQUEST';
export const GET_SINGLE_CONTACTADDRESS_SUCCESS = 'GET_SINGLE_CONTACTADDRESS_SUCCESS';
export const GET_SINGLE_CONTACTADDRESS_FAIL = 'GET_SINGLE_CONTACTADDRESS_FAIL';
export const GET_SINGLE_CONTACTADDRESS_RESET = 'GET_SINGLE_CONTACTADDRESS_RESET';

export const UPDATE_SINGLE_CONTACTADDRESS_REQUEST = "UPDATE_SINGLE_CONTACTADDRESS_REQUEST";
export const UPDATE_SINGLE_CONTACTADDRESS_SUCCESS = "UPDATE_SINGLE_CONTACTADDRESS_SUCCESS";
export const UPDATE_SINGLE_CONTACTADDRESS_FAIL = "UPDATE_SINGLE_CONTACTADDRESS_FAIL";
export const UPDATE_SINGLE_CONTACTADDRESS_RESET = "UPDATE_SINGLE_CONTACTADDRESS_RESET";