export const GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_REQUEST =
  "GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_REQUEST";
export const GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_SUCCESS =
  "GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_SUCCESS";
export const GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_FAIL =
  "GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_FAIL";
export const GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_RESET =
  "GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_RESET";

export const GET_EXAM_SCHEDULE_LIST_REQUEST = "GET_EXAM_SCHEDULE_LIST_REQUEST";
export const GET_EXAM_SCHEDULE_LIST_SUCCESS = "GET_EXAM_SCHEDULE_LIST_SUCCESS";
export const GET_EXAM_SCHEDULE_LIST_FAIL = "GET_EXAM_SCHEDULE_LIST_FAIL";
