export const GET_ALL_TRAINING_REQUEST = 'GET_ALL_TRAINING_REQUEST';
export const GET_ALL_TRAINING_SUCCESS = 'GET_ALL_TRAINING_SUCCESS';
export const GET_ALL_TRAINING_FAIL = 'GET_ALL_TRAINING_FAIL';
export const GET_ALL_TRAINING_RESET = 'GET_ALL_TRAINING_RESET';

export const GET_ALL_TRAINING_CREATE_REQUEST = 'GET_ALL_TRAINING_CREATE_REQUEST';
export const GET_ALL_TRAINING_CREATE_SUCCESS = 'GET_ALL_TRAINING_CREATE_SUCCESS';
export const GET_ALL_TRAINING_CREATE_FAIL = 'GET_ALL_TRAINING_CREATE_FAIL';
export const GET_ALL_TRAINING_CREATE_RESET = 'GET_ALL_TRAINING_CREATE_RESET';

export const CREATE_SINGLE_TRAINING_REQUEST = "CREATE_SINGLE_TRAINING_REQUEST";
export const CREATE_SINGLE_TRAINING_SUCCESS = "CREATE_SINGLE_TRAINING_SUCCESS";
export const CREATE_SINGLE_TRAINING_FAIL = "CREATE_SINGLE_TRAINING_FAIL";
export const CREATE_SINGLE_TRAINING_RESET = "CREATE_SINGLE_TRAINING_RESET";

export const TRAINING_CREATE_REQUEST = 'TRAINING_CREATE_REQUEST';
export const TRAINING_CREATE_SUCCESS = 'TRAINING_CREATE_SUCCESS';
export const TRAINING_CREATE_FAIL = 'TRAINING_CREATE_FAIL';
export const TRAINING_CREATE_RESET = 'TRAINING_CREATE_RESET';