export const GET_EXAM_MARK_APPROVAL_INITIAL_DATA_REQUEST =
  "GET_EXAM_MARK_APPROVAL_INITIAL_DATA_REQUEST";
export const GET_EXAM_MARK_APPROVAL_INITIAL_DATA_SUCCESS =
  "GET_EXAM_MARK_APPROVAL_INITIAL_DATA_SUCCESS";
export const GET_EXAM_MARK_APPROVAL_INITIAL_DATA_FAIL =
  "GET_EXAM_MARK_APPROVAL_INITIAL_DATA_FAIL";
export const GET_EXAM_MARK_APPROVAL_INITIAL_DATA_RESET =
  "GET_EXAM_MARK_APPROVAL_INITIAL_DATA_RESET";

export const GET_ALL_EXAM_MARK_APPROVAL_SEARCHDATA_REQUEST =
  "GET_ALL_EXAM_MARK_APPROVAL_SEARCHDATA_REQUEST";
export const GET_ALL_EXAM_MARK_APPROVAL_SEARCHDATA_SUCCESS =
  "GET_ALL_EXAM_MARK_APPROVAL_SEARCHDATA_SUCCESS";
export const GET_ALL_EXAM_MARK_APPROVAL_SEARCHDATA_FAIL =
  "GET_ALL_EXAM_MARK_APPROVAL_SEARCHDATA_FAIL";
export const GET_ALL_EXAM_MARK_APPROVAL_SEARCHDATA_RESET =
  "GET_ALL_EXAM_MARK_APPROVAL_SEARCHDATA_RESET";

export const GET_EXAM_MARK_APPROVAL_SCHEULE_HEADER_REQUEST =
  "GET_EXAM_MARK_APPROVAL_SCHEULE_HEADER_REQUEST";
export const GET_EXAM_MARK_APPROVAL_SCHEULE_HEADER_SUCCESS =
  "GET_EXAM_MARK_APPROVAL_SCHEULE_HEADER_SUCCESS";
export const GET_EXAM_MARK_APPROVAL_SCHEULE_HEADER_FAIL =
  "GET_EXAM_MARK_APPROVAL_SCHEULE_HEADER_FAIL";
export const GET_EXAM_MARK_APPROVAL_SCHEULE_HEADER_RESET =
  "GET_EXAM_MARK_APPROVAL_SCHEULE_HEADER_RESET";

export const GET_BULK_EXAM_MARK_APPROVAL_REQUEST =
  "GET_BULK_EXAM_MARK_APPROVAL_REQUEST";
export const GET_BULK_EXAM_MARK_APPROVAL_SUCCESS =
  "GET_BULK_EXAM_MARK_APPROVAL_SUCCESS";
export const GET_BULK_EXAM_MARK_APPROVAL_FAIL =
  "GET_BULK_EXAM_MARK_APPROVAL_FAIL";
export const GET_BULK_EXAM_MARK_APPROVAL_RESET =
  "GET_BULK_EXAM_MARK_APPROVAL_RESET";

export const POST_BULK_EXAM_MARK_APPROVAL_REQUEST =
  "POST_BULK_EXAM_MARK_APPROVAL_REQUEST";
export const POST_BULK_EXAM_MARK_APPROVAL_SUCCESS =
  "POST_BULK_EXAM_MARK_APPROVAL_SUCCESS";
export const POST_BULK_EXAM_MARK_APPROVAL_FAIL =
  "POST_BULK_EXAM_MARK_APPROVAL_FAIL";
export const POST_BULK_EXAM_MARK_APPROVAL_RESET =
  "POST_BULK_EXAM_MARK_APPROVAL_RESET";

  export const GET_ALL_OTHER_OPTIONS_FOR_SELECT_TEACHER_REQUEST =
  "GET_ALL_OTHER_OPTIONS_FOR_SELECT_TEACHER_REQUEST";
export const GET_ALL_OTHER_OPTIONS_FOR_SELECT_TEACHER_SUCCESS =
  "GET_ALL_OTHER_OPTIONS_FOR_SELECT_TEACHER_SUCCESS";
export const GET_ALL_OTHER_OPTIONS_FOR_SELECT_TEACHER_FAIL =
  "GET_ALL_OTHER_OPTIONS_FOR_SELECT_TEACHER_FAIL";
export const GET_ALL_OTHER_OPTIONS_FOR_SELECT_TEACHER_RESET =
  "GET_ALL_OTHER_OPTIONS_FOR_SELECT_TEACHER_RESET";

  export const GET_ACTIVE_SUBJECT_REQUEST =
  "GET_ACTIVE_SUBJECT_REQUEST";
export const GET_ACTIVE_SUBJECT_SUCCESS =
  "GET_ACTIVE_SUBJECT_SUCCESS";
export const GET_ACTIVE_SUBJECT_FAIL =
  "GET_ACTIVE_SUBJECT_FAIL";
export const GET_ACTIVE_SUBJECT_RESET =
  "GET_ACTIVE_SUBJECT_RESET";
