export const GET_ALL_JOBHISTORY_REQUEST = 'GET_ALL_JOBHISTORY_REQUEST';
export const GET_ALL_JOBHISTORY_SUCCESS = 'GET_ALL_JOBHISTORY_SUCCESS';
export const GET_ALL_JOBHISTORY_FAIL = 'GET_ALL_JOBHISTORY_FAIL';
export const GET_ALL_JOBHISTORY_RESET = 'GET_ALL_JOBHISTORY_RESET';

export const GET_ALL_JOBHISTORY_CREATE_REQUEST = 'GET_ALL_JOBHISTORY_CREATE_REQUEST';
export const GET_ALL_JOBHISTORY_CREATE_SUCCESS = 'GET_ALL_JOBHISTORY_CREATE_SUCCESS';
export const GET_ALL_JOBHISTORY_CREATE_FAIL = 'GET_ALL_JOBHISTORY_CREATE_FAIL';
export const GET_ALL_JOBHISTORY_CREATE_RESET = 'GET_ALL_JOBHISTORY_CREATE_RESET';

export const CREATE_SINGLE_JOBHISTORY_REQUEST = "CREATE_SINGLE_JOBHISTORY_REQUEST";
export const CREATE_SINGLE_JOBHISTORY_SUCCESS = "CREATE_SINGLE_JOBHISTORY_SUCCESS";
export const CREATE_SINGLE_JOBHISTORY_FAIL = "CREATE_SINGLE_JOBHISTORY_FAIL";
export const CREATE_SINGLE_JOBHISTORY_RESET = "CREATE_SINGLE_JOBHISTORY_RESET";

export const JOBHISTORY_CREATE_REQUEST = 'JOBHISTORY_CREATE_REQUEST';
export const JOBHISTORY_CREATE_SUCCESS = 'JOBHISTORY_CREATE_SUCCESS';
export const JOBHISTORY_CREATE_FAIL = 'JOBHISTORY_CREATE_FAIL';
export const JOBHISTORY_CREATE_RESET = 'JOBHISTORY_CREATE_RESET';