export const GET_ALL_ASSIGNMENT_TEACHER_REQUEST =
  "GET_ALL_ASSIGNMENT_TEACHER_REQUEST";
export const GET_ALL_ASSIGNMENT_TEACHER_SUCCESS =
  "GET_ALL_ASSIGNMENT_TEACHER_SUCCESS";
export const GET_ALL_ASSIGNMENT_TEACHER_FAIL =
  "GET_ALL_ASSIGNMENT_TEACHER_FAIL";
export const GET_ALL_ASSIGNMENT_TEACHER_RESET =
  "GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_RESET";

export const GET_ALL_OTHER_OPTIONS_FOR_SELECT_REQUEST =
  "GET_ALL_OTHER_OPTIONS_FOR_SELECT_REQUEST";
export const GET_ALL_OTHER_OPTIONS_FOR_SELECT_SUCCESS =
  "GET_ALL_OTHER_OPTIONS_FOR_SELECT_SUCCESS";
export const GET_ALL_OTHER_OPTIONS_FOR_SELECT_FAIL =
  "GET_ALL_OTHER_OPTIONS_FOR_SELECT_FAIL";
export const GET_ALL_OTHER_OPTIONS_FOR_SELECT_RESET =
  "GET_ALL_OTHER_OPTIONS_FOR_SELECT_RESET";

export const GET_LIST_TEACHER_ASSIGNMENT_REQUEST =
  "GET_LIST_TEACHER_ASSIGNMENT_REQUEST";
export const GET_LIST_TEACHER_ASSIGNMENT_SUCCESS =
  "GET_LIST_TEACHER_ASSIGNMENT_SUCCESS";
export const GET_LIST_TEACHER_ASSIGNMENT_FAIL =
  "GET_LIST_TEACHER_ASSIGNMENT_FAIL";
export const GET_LIST_TEACHER_ASSIGNMENT_RESET =
  "GET_LIST_TEACHER_ASSIGNMENT_RESET";

export const GET_ENGLISH_DATE_REQUEST = "GET_ENGLISH_DATE_REQUEST";
export const GET_ENGLISH_DATE_SUCCESS = "GET_ENGLISH_DATE_SUCCESS";
export const GET_ENGLISH_DATE_FAIL = "GET_ENGLISH_DATE_FAIL";
export const GET_ENGLISH_DATE_RESET = "GET_ENGLISH_DATE_RESET";

export const GET_SINGLE_CREATE_TEACHER_ASSIGNMENT_REQUEST =
  "GET_SINGLE_CREATE_TEACHER_ASSIGNMENT_REQUEST";
export const GET_SINGLE_CREATE_TEACHER_ASSIGNMENT_SUCCESS =
  "GET_SINGLE_CREATE_TEACHER_ASSIGNMENT_SUCCESS";
export const GET_SINGLE_CREATE_TEACHER_ASSIGNMENT_FAIL =
  "GET_SINGLE_CREATE_TEACHER_ASSIGNMENT_FAIL";
export const GET_SINGLE_CREATE_TEACHER_ASSIGNMENT_RESET =
  "GET_SINGLE_CREATE_TEACHER_ASSIGNMENT_RESET";

export const POST_TEACHER_ASSIGNMENT_REQUEST =
  "POST_TEACHER_ASSIGNMENT_REQUEST";
export const POST_TEACHER_ASSIGNMENT_SUCCESS =
  "POST_TEACHER_ASSIGNMENT_SUCCESS";
export const POST_TEACHER_ASSIGNMENT_FAIL = "POST_TEACHER_ASSIGNMENT_FAIL";
export const POST_TEACHER_ASSIGNMENT_RESET = "POST_TEACHER_ASSIGNMENT_RESET";

export const GET_TEACHER_ASSIGNMENT_CONTENT_REQUEST =
  "GET_TEACHER_ASSIGNMENT_CONTENT_REQUEST";
export const GET_TEACHER_ASSIGNMENT_CONTENT_SUCCESS =
  "GET_TEACHER_ASSIGNMENT_CONTENT_SUCCESS";
export const GET_TEACHER_ASSIGNMENT_CONTENT_FAIL =
  "GET_TEACHER_ASSIGNMENT_CONTENT_FAIL";
export const GET_TEACHER_ASSIGNMENT_CONTENT_RESET =
  "GET_TEACHER_ASSIGNMENT_CONTENT_RESET";

export const GET_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_REQUEST =
  "GET_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_REQUEST";
export const GET_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_SUCCESS =
  "GET_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_SUCCESS";
export const GET_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_FAIL =
  "GET_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_FAIL";
export const GET_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_RESET =
  "GET_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_RESET";

export const PUT_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_REQUEST =
  "PUT_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_REQUEST";
export const PUT_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_SUCCESS =
  "PUT_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_SUCCESS";
export const PUT_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_FAIL =
  "PUT_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_FAIL";
export const PUT_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_RESET =
  "PUT_SINGLE_TO_EDIT_TEACHER_ASSIGNMENT_RESET";

export const DOWNLOAD_ASSIGNMENT_REQUEST = "DOWNLOAD_ASSIGNMENT_REQUEST";
export const DOWNLOAD_ASSIGNMENT_SUCCESS = "DOWNLOAD_ASSIGNMENT_SUCCESS";
export const DOWNLOAD_ASSIGNMENT_FAIL = "DOWNLOAD_ASSIGNMENT_FAIL";
export const DOWNLOAD_ASSIGNMENT_RESET = "DOWNLOAD_ASSIGNMENT_RESET";

export const DOWNLOAD_SUBMITTED_ASSIGNMENT_REQUEST = "DOWNLOAD_SUBMITTED_ASSIGNMENT_REQUEST";
export const DOWNLOAD_SUBMITTED_ASSIGNMENT_SUCCESS = "DOWNLOAD_SUBMITTED_ASSIGNMENT_SUCCESS";
export const DOWNLOAD_SUBMITTED_ASSIGNMENT_FAIL = "DOWNLOAD_SUBMITTED_ASSIGNMENT_FAIL";
export const DOWNLOAD_SUBMITTED_ASSIGNMENT_RESET = "DOWNLOAD_SUBMITTED_ASSIGNMENT_RESET";
