export const GET_ALL_EXAM_DIVISION_REQUEST = "GET_ALL_EXAM_DIVISION_REQUEST";
export const GET_ALL_EXAM_DIVISION_SUCCESS = "GET_ALL_EXAM_DIVISION_SUCCESS";
export const GET_ALL_EXAM_DIVISION_FAIL = "GET_ALL_EXAM_DIVISION_FAIL";
export const GET_ALL_EXAM_DIVISION_RESET = "GET_ALL_EXAM_DIVISION_RESET";

export const GET_SINGLE_EXAM_DIVISION_REQUEST =
  "GET_SINGLE_EXAM_DIVISION_REQUEST";
export const GET_SINGLE_EXAM_DIVISION_SUCCESS =
  "GET_SINGLE_EXAM_DIVISION_SUCCESS";
export const GET_SINGLE_EXAM_DIVISION_FAIL = "GET_SINGLE_EXAM_DIVISION_FAIL";
export const GET_SINGLE_EXAM_DIVISION_RESET = "GET_SINGLE_EXAM_DIVISION_RESET";

export const CREATE_EXAM_DIVISION_REQUEST = "CREATE_EXAM_DIVISION_REQUEST";
export const CREATE_EXAM_DIVISION_SUCCESS = "CREATE_EXAM_DIVISION_SUCCESS";
export const CREATE_EXAM_DIVISION_FAIL = "CREATE_EXAM_DIVISION_FAIL";
export const CREATE_EXAM_DIVISION_RESET = "CREATE_EXAM_DIVISION_RESET";

export const GET_SINGLE_EXAM_DIVISION_EDIT_REQUEST =
  "GET_SINGLE_EXAM_DIVISION_EDIT_REQUEST";
export const GET_SINGLE_EXAM_DIVISION_EDIT_SUCCESS =
  "GET_SINGLE_EXAM_DIVISION_EDIT_SUCCESS";
export const GET_SINGLE_EXAM_DIVISION_EDIT_FAIL =
  "GET_SINGLE_EXAM_DIVISION_EDIT_FAIL";
export const GET_SINGLE_EXAM_DIVISION_EDIT_RESET =
  "GET_SINGLE_EXAM_DIVISION_EDIT_RESET";

export const UPDATE_SINGLE_EXAM_DIVISION_REQUEST =
  "UPDATE_SINGLE_EXAM_DIVISION_REQUEST";
export const UPDATE_SINGLE_EXAM_DIVISION_SUCCESS =
  "UPDATE_SINGLE_EXAM_DIVISION_SUCCESS";
export const UPDATE_SINGLE_EXAM_DIVISION_FAIL =
  "UPDATE_SINGLE_EXAM_DIVISION_FAIL";
export const UPDATE_SINGLE_EXAM_DIVISION_RESET =
  "UPDATE_SINGLE_EXAM_DIVISION_RESET";
