export const GET_ALL_PG_CLASS_SCHEDULE_REQUEST =
  "GET_ALL_PG_CLASS_SCHEDULE_REQUEST";
export const GET_ALL_PG_CLASS_SCHEDULE_SUCCESS =
  "GET_ALL_PG_CLASS_SCHEDULE_SUCCESS";
export const GET_ALL_PG_CLASS_SCHEDULE_FAIL = "GET_ALL_PG_CLASS_SCHEDULE_FAIL";
export const GET_ALL_PG_CLASS_SCHEDULE_RESET =
  "GET_ALL_PG_CLASS_SCHEDULE_RESET";

export const GET_LIST_CLASS_SCHEDULE_REQUEST =
  "GET_LIST_CLASS_SCHEDULE_REQUEST";
export const GET_LIST_CLASS_SCHEDULE_SUCCESS =
  "GET_LIST_CLASS_SCHEDULE_SUCCESS";
export const GET_LIST_CLASS_SCHEDULE_FAIL = "GET_LIST_CLASS_SCHEDULE_FAIL";
export const GET_LIST_CLASS_SCHEDULE_RESET = "GET_LIST_CLASS_SCHEDULE_RESET";

// export const GET_EDIT_CLASS_SCHEDULE_REQUEST =
//   "GET_EDIT_CLASS_SCHEDULE_REQUEST";
// export const GET_EDIT_CLASS_SCHEDULE_SUCCESS =
//   "GET_EDIT_CLASS_SCHEDULE_SUCCESS";
// export const GET_EDIT_CLASS_SCHEDULE_FAIL = "GET_EDIT_CLASS_SCHEDULE_FAIL";
// export const GET_EDIT_CLASS_SCHEDULE_RESET = "GET_EDIT_CLASS_SCHEDULE_RESET";

// export const PUT_CLASS_SCHEDULE_REQUEST = "PUT_CLASS_SCHEDULE_REQUEST";
// export const PUT_CLASS_SCHEDULE_SUCCESS = "PUT_CLASS_SCHEDULE_SUCCESS";
// export const PUT_CLASS_SCHEDULE_FAIL = "PUT_CLASS_SCHEDULE_FAIL";
// export const PUT_CLASS_SCHEDULE_RESET = "PUT_CLASS_SCHEDULE_RESET";
