export const GET_HEADER_CONTENT_REQUEST = "GET_HEADER_CONTENT_REQUEST";
export const GET_HEADER_CONTENT_SUCCESS = "GET_HEADER_CONTENT_SUCCESS";
export const GET_HEADER_CONTENT_FAIL = "GET_HEADER_CONTENT_FAIL";
export const GET_HEADER_CONTENT_RESET = "GET_HEADER_CONTENT_RESET";

export const GET_TEACHER_DASHBOARD_REQUEST = "GET_TEACHER_DASHBOARD_REQUEST";
export const GET_TEACHER_DASHBOARD_SUCCESS = "GET_TEACHER_DASHBOARD_SUCCESS";
export const GET_TEACHER_DASHBOARD_FAIL = "GET_TEACHER_DASHBOARD_FAIL";
export const GET_TEACHER_DASHBOARD_RESET = "GET_TEACHER_DASHBOARD_RESET";
