export const GET_ALL_TOTAL_STUDENT_ATTENDANCE_REQUEST =
  "GET_ALL_TOTAL_STUDENT_ATTENDANCE_REQUEST";
export const GET_ALL_TOTAL_STUDENT_ATTENDANCE_SUCCESS =
  "GET_ALL_TOTAL_STUDENT_ATTENDANCE_SUCCESS";
export const GET_ALL_TOTAL_STUDENT_ATTENDANCE_FAIL =
  "GET_ALL_TOTAL_STUDENT_ATTENDANCE_FAIL";
export const GET_ALL_TOTAL_STUDENT_ATTENDANCE_RESET =
  "GET_ALL_TOTAL_STUDENT_ATTENDANCE_RESET";

export const GET_LIST_TOTAL_STUDENT_ATTENDANCE_REQUEST =
  "GET_LIST_TOTAL_STUDENT_ATTENDANCE_REQUEST";
export const GET_LIST_TOTAL_STUDENT_ATTENDANCE_SUCCESS =
  "GET_LIST_TOTAL_STUDENT_ATTENDANCE_SUCCESS";
export const GET_LIST_TOTAL_STUDENT_ATTENDANCE_FAIL =
  "GET_LIST_TOTAL_STUDENT_ATTENDANCE_FAIL";
export const GET_LIST_TOTAL_STUDENT_ATTENDANCE_RESET =
  "GET_LIST_TOTAL_STUDENT_ATTENDANCE_RESET";
