export const GET_ALL_HOBBY_REQUEST = 'GET_ALL_HOBBY_REQUEST';
export const GET_ALL_HOBBY_SUCCESS = 'GET_ALL_HOBBY_SUCCESS';
export const GET_ALL_HOBBY_FAIL = 'GET_ALL_HOBBY_FAIL';
export const GET_ALL_HOBBY_RESET = 'GET_ALL_HOBBY_RESET';

// export const GET_SINGLE_HOBBY_REQUEST = 'GET_SINGLE_HOBBY_REQUEST';
// export const GET_SINGLE_HOBBY_SUCCESS = 'GET_SINGLE_HOBBY_SUCCESS';
// export const GET_SINGLE_HOBBY_FAIL = 'GET_SINGLE_HOBBY_FAIL';
// export const GET_SINGLE_HOBBY_RESET = 'GET_SINGLE_HOBBY_RESET';

export const GET_ALL_HOBBY_CREATE_REQUEST = 'GET_ALL_HOBBY_CREATE_REQUEST';
export const GET_ALL_HOBBY_CREATE_SUCCESS = 'GET_ALL_HOBBY_CREATE_SUCCESS';
export const GET_ALL_HOBBY_CREATE_FAIL = 'GET_ALL_HOBBY_CREATE_FAIL';
export const GET_ALL_HOBBY_CREATE_RESET = 'GET_ALL_HOBBY_CREATE_RESET';

export const CREATE_SINGLE_HOBBY_REQUEST = "CREATE_SINGLE_HOBBY_REQUEST";
export const CREATE_SINGLE_HOBBY_SUCCESS = "CREATE_SINGLE_HOBBY_SUCCESS";
export const CREATE_SINGLE_HOBBY_FAIL = "CREATE_SINGLE_HOBBY_FAIL";
export const CREATE_SINGLE_HOBBY_RESET = "CREATE_SINGLE_HOBBY_RESET";

export const HOBBY_CREATE_REQUEST = 'HOBBY_CREATE_REQUEST';
export const HOBBY_CREATE_SUCCESS = 'HOBBY_CREATE_SUCCESS';
export const HOBBY_CREATE_FAIL = 'HOBBY_CREATE_FAIL';
export const HOBBY_CREATE_RESET = 'HOBBY_CREATE_RESET';