export const GET_ALL_ACADEMIC_STUDENT_EXAMDATA_REQUEST =
  "GET_ALL_ACADEMIC_STUDENT_EXAMDATA_REQUEST";
export const GET_ALL_ACADEMIC_STUDENT_EXAMDATA_SUCCESS =
  "GET_ALL_ACADEMIC_STUDENT_EXAMDATA_SUCCESS";
export const GET_ALL_ACADEMIC_STUDENT_EXAMDATA_FAIL =
  "GET_ALL_ACADEMIC_STUDENT_EXAMDATA_FAIL";

export const GET_EVENT_REQUEST = "GET_EVENT_REQUEST";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_EVENT_FAIL = "GET_EVENT_FAIL";
export const GET_EVENT_RESET = "GET_EVENT_RESET";

export const GET_EXAM_SCHEDULE_HEADER_REQUEST =
  "GET_EXAM_SCHEDULE_HEADER_REQUEST";
export const GET_EXAM_SCHEDULE_HEADER_SUCCESS =
  "GET_EXAM_SCHEDULE_HEADER_SUCCESS";
export const GET_EXAM_SCHEDULE_HEADER_FAIL = "GET_EVENT_FAIL";
export const GET_EXAM_SCHEDULE_HEADER_RESET = "GET_EXAM_SCHEDULE_HEADER_RESET";

export const GET_ALL_EXAM_ENTRY_SEARCHDATA_REQUEST =
  "GET_ALL_EXAM_ENTRY_SEARCHDATA_REQUEST";
export const GET_ALL_EXAM_ENTRY_SEARCHDATA_SUCCESS =
  "GET_ALL_EXAM_ENTRY_SEARCHDATA_SUCCESS";
export const GET_ALL_EXAM_ENTRY_SEARCHDATA_FAIL =
  "GET_ALL_EXAM_ENTRY_SEARCHDATA_FAIL";

export const GET_ALL_EXAM_ENTRY_BULK_REQUEST =
  "GET_ALL_EXAM_ENTRY_BULK_REQUEST";
export const GET_ALL_EXAM_ENTRY_BULK_SUCCESS =
  "GET_ALL_EXAM_ENTRY_BULK_SUCCESS";
export const GET_ALL_EXAM_ENTRY_BULK_FAIL = "GET_ALL_EXAM_ENTRY_BULK_FAIL";
