export const GET_ALL_SKILL_REQUEST = 'GET_ALL_SKILL_REQUEST';
export const GET_ALL_SKILL_SUCCESS = 'GET_ALL_SKILL_SUCCESS';
export const GET_ALL_SKILL_FAIL = 'GET_ALL_SKILL_FAIL';
export const GET_ALL_SKILL_RESET = 'GET_ALL_SKILL_RESET';

export const GET_ALL_SKILL_CREATE_REQUEST = 'GET_ALL_SKILL_CREATE_REQUEST';
export const GET_ALL_SKILL_CREATE_SUCCESS = 'GET_ALL_SKILL_CREATE_SUCCESS';
export const GET_ALL_SKILL_CREATE_FAIL = 'GET_ALL_SKILL_CREATE_FAIL';
export const GET_ALL_SKILL_CREATE_RESET = 'GET_ALL_SKILL_CREATE_RESET';

export const CREATE_SINGLE_SKILL_REQUEST = "CREATE_SINGLE_SKILL_REQUEST";
export const CREATE_SINGLE_SKILL_SUCCESS = "CREATE_SINGLE_SKILL_SUCCESS";
export const CREATE_SINGLE_SKILL_FAIL = "CREATE_SINGLE_SKILL_FAIL";
export const CREATE_SINGLE_SKILL_RESET = "CREATE_SINGLE_SKILL_RESET";

export const SKILL_CREATE_REQUEST = 'SKILL_CREATE_REQUEST';
export const SKILL_CREATE_SUCCESS = 'SKILL_CREATE_SUCCESS';
export const SKILL_CREATE_FAIL = 'SKILL_CREATE_FAIL';
export const SKILL_CREATE_RESET = 'SKILL_CREATE_RESET';